### PR TITLE
Maleaume clean code

### PR DESCRIPTION
**Pull request by Maleaume**
I Propose Some refactoring on our code.
Simplification and optimization.

enjoy

### CODE REVIEW

**Comment by MalauD** [comment]
Thank you so much, you are simply a god !
So i'mgoing to do some test and fork it if everything is ok.
Thank you again !

**Comment by MalauD** [comment]
Let me just reopen it

**Comment by MalauD** [comment]
No problem !
Adding the album name to the hash function is a good idea i'm going to try it. And yes i just replace it with FirstOrDefault to not throw an exception.
Thanks a lot for your suggestion !

**Comment by MalauD** [comment]
So i changed the hash function and revert to `SingleOrDefault` and it seems to work fine !

**Comment by Maleaume** [comment]
Great  !!

**Comment by MalauD** [comment]
After doing some test on the upload of the music there is some exception that i will try to fix.

**Comment by Maleaume** [comment]
It will be important to have some UnitTests in our project.
Unit Test for Server, and some other test for the client but those tests must be independant.

If you need help, I'm here

**Comment by MalauD** [comment]
Hi, I have a slack server that could be useful but i need an email so contact me at malaurydutour@outlook.fr

**Comment by MalauD** [comment]
Now the upload seems to work well. I just remove some unused field in IElement children (Music, Album, Artist, Playlist classes)

**Comment by MalauD** [comment]
Ok so now you can can switch on or off the multithreading with the command `-set multithreading true/false`

**Pull request merged**
